          APP_ID=$(awk -F '"' '/applicationId( |=)/ {print $2; exit}' $BUILD_GRADLE)
          sed -E "/applicationId( |=)/s|${APP_ID}|${NEW_APP_ID}|" -i $BUILD_GRADLE
          # sed -E '/applicationId( |=)/s|com\.draco\.ladb|bff.ladb|' -i app/build.gradle
