name: Build - PackageManager

on:
  workflow_dispatch:

env:
  FLAV: "pro"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "SmartPack/PackageManager"
          ref: "master"

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Change versionCode To Max INT
        run: |
          BUILD_GRADLE=$(find app -maxdepth 1 \( -name 'build.gradle' -or -name 'build.gradle.kts' \) -print -quit)
          ### Do this because some use ```versionName = versionCode.toString()``` ###
          OLD_VER_CODE=$(awk '/^\s*versionCode/ {print $NF; exit}' $BUILD_GRADLE)
          sed -E "/^\s*versionName/s/versionCode\.toString\(\)/\"${OLD_VER_CODE}\"/" -i $BUILD_GRADLE
          ###
          sed -E '/^\s*versionCode/s/[0-9]+$/2147483647/' -i $BUILD_GRADLE

      - name: Change app and package name
        run: |
          BUILD_GRADLE=$(find app -maxdepth 1 \( -name 'build.gradle' -or -name 'build.gradle.kts' \) -print -quit)
          APP_ID=$(awk -F '"' '/applicationId( |=)/ {print $2; exit}' $BUILD_GRADLE)
          ### The android:label attribute within the <application> tag of the AndroidManifest.xml file specifies the name of the Android application
          ### android:label="@string/app_name" references a string resource named app_name.
          ### This is the recommended practice for defining the application name
          ### If someone uses a name other than app_name, then find the android:label from this command.
          ### xq -j app/src/main/AndroidManifest.xml | jq -r '.manifest.application."@label"' | cut -f2 -d'/'
          ### https://github.com/sibprogrammer/xq/
          ### Maybe loop through (find app -name '*.xml')
          APP_NAME=$(awk -F'[<>]' '/name="app_name"/ {print $3}' app/src/main/res/values/strings.xml)
          for xml in $(find app -name '*.xml' -exec grep -l "app_name" {} + ); do
            if [ -n "${APP_NAME}" ]; then
              break;
            fi;
            APP_NAME=$(awk -F'[<>]' '/name="app_name"/ {print $3}' $xml);
          done
          # Sometime they set this way
          [[ -z "${APP_NAME}" ]] && APP_NAME=$(awk -F'[,"]' '/resValue.*app_name/ {print $(NF-1)}' $BUILD_GRADLE)
          APP_NAME="${APP_NAME// /}"
          NEW_APP_ID="bff.${APP_NAME,,}${FLAV:+".$FLAV"}"
          sed -E "/applicationId( |=)/s|${APP_ID}|${NEW_APP_ID}|" -i $BUILD_GRADLE
          echo "APP_NAME=${APP_NAME}" >> $GITHUB_ENV

      - name: Remove Pre-defined APK Name
        run: |
          BUILD_GRADLE=$(find app -maxdepth 1 \( -name 'build.gradle' -or -name 'build.gradle.kts' \) -print -quit)
          sed -E '/archives(Base)*Name/d' -i $BUILD_GRADLE

      - run: yes | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses
      
      - name: Build release APK
        run: |
          chmod +x ./gradlew
          ./gradlew :app:assemble${FLAV^}Release

      - name: List APKs
        run: find app -name '*.apk'

      - name: Set Env
        run: |
          APK_PATH_PREFIX="app/build/outputs/apk/${FLAV:+$FLAV/}release"
          # APK_UNSIGNED_NAME="app${FLAV:+"-$FLAV"}-release-unsigned.apk"
          APK_FILE=$(find ${APK_PATH_PREFIX} \( -iname "app${FLAV:+"-$FLAV"}-release-unsigned.apk" -o -iname "app${FLAV:+"-$FLAV"}-release.apk" -o -iname '*arm64-v8*' \) -print -quit)
          echo "APK_PATH_PREFIX=${APK_PATH_PREFIX}" >> $GITHUB_ENV
          echo "APK_UNSIGNED_NAME=${APK_UNSIGNED_NAME}" >> $GITHUB_ENV
          echo "APK_FILE=${APK_FILE}" >> $GITHUB_ENV

      - name: Sign APK
        env:
          KEYSTORE: ${{ secrets.SIGNING_KEY }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: |
          echo "${KEYSTORE}" | base64 -d > apksign.keystore
          versionName=$( jq -r '.elements[0].versionName' ${APK_PATH_PREFIX}/output-metadata.json )
          # APK_UNSIGNED_NAME="app${FLAV:+"-$FLAV"}-release-unsigned.apk"
          # ${ANDROID_HOME}/build-tools/36.0.0/apksigner sign --ks apksign.keystore --ks-pass env:SIGNING_STORE_PASSWORD ${APK_PATH_PREFIX}/${APK_UNSIGNED_NAME}

          for apk in ${APK_PATH_PREFIX}/*.apk; do ${ANDROID_HOME}/build-tools/36.0.0/apksigner sign --ks apksign.keystore --ks-pass env:SIGNING_STORE_PASSWORD $apk; done

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_APK_REPO }}
          # GH_TOKEN: ${{ github.token }}
        run: |
          versionName=$( jq -r '.elements[0].versionName' ${APK_PATH_PREFIX}/output-metadata.json )
          APP_FLAV_NAME="${APP_NAME}${FLAV:+"-$FLAV"}"
          mv ${APK_FILE} ${APK_PATH_PREFIX}/${APP_FLAV_NAME}_${versionName}.apk
          gh release create "${versionName}-${APP_FLAV_NAME}" --title "${APP_FLAV_NAME} ${versionName}" --repo wrppg/apk ${APK_PATH_PREFIX}/*.apk --notes $'Automate build\n'"update to ${versionName}"

          # gh release upload "${versionName}-${APP_FLAV_NAME}" ${APK_PATH_PREFIX}/*.apk
