name: Main - Build

on:
  workflow_dispatch:
    inputs:
      repo:
        required: true
        type: string
      ref:
        required: true
        type: string
        default: "default"
      vercode:
        required: false
        type: string
      java:
        required: false
        type: string
        default: "17"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ${{ github.event.inputs.repo }} - ${{ github.event.inputs.vercode }}
        run: echo ${{ github.event.inputs.repo }}

      - name: find default branch
        id: find-default-branch
        if: github.event.inputs.ref == 'default'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          BRANCH_REF=$(gh repo view ${{ github.event.inputs.repo }} --json defaultBranchRef --jq '.defaultBranchRef.name')
          # BRANCH_REF=$(gh api https://api.github.com/repos/${{ github.event.inputs.repo }} --jq '.default_branch')

          echo "branch_ref=$BRANCH_REF" >> $GITHUB_OUTPUT
      
      - uses: actions/checkout@v6
        with:
          repository: ${{ github.event.inputs.repo }}
          ref: ${{ steps.find-default-branch.outputs.branch_ref  || github.event.inputs.ref }}

      - uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          # java-version: "17"
          java-version: ${{ github.event.inputs.java || '17' }}
          cache: "gradle"

      - name: Run script
        env:
          KEYSTORE: ${{ secrets.SIGNING_KEY }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: |
          curl -sfL https://raw.githubusercontent.com/wrppg/bff/refs/heads/main/run.sh | bash -s -- ${{ github.event.inputs.repo }}

      - name: Check env
        run: |
          echo "APP_NAME=$APP_NAME"
          echo "FLAV=$FLAV"
          echo "IV_IC_COLOR=$IV_IC_COLOR"

      - id: cache-magick
        if: env.IV_IC_COLOR == 'yes'
        uses: actions/cache@v5
        with:
          path: ~/bin/magick
          key: ${{ runner.os }}-bin-magick-7.1.2-19
          restore-keys: |
            ${{ runner.os }}-bin-

      - name: Install magick
        if: steps.cache-magick.outputs.cache-hit != 'true' && env.IV_IC_COLOR == 'yes'
        run: |
          mkdir -p ~/bin
          curl -L https://download.imagemagick.org/archive/binaries/magick --output-dir ~/bin -o magick
          chmod +x ~/bin/*

      - name: Add bin to PATH
        run: echo "$HOME/bin" >> $GITHUB_PATH

      - name: Inverse Colour Launcher Icon
        if: env.IV_IC_COLOR == 'yes'
        run: |
          ic_launcher_name=$(find app/src/ -type f -name 'AndroidManifest.xml' \
          -exec yq -r --xml-attribute-prefix "+@" -p=xml -o=json '.manifest.application."+@android:icon"' {} \; | \
          cut -f2 -d "/")

          ic_launcher_ext="$(find app/src/ -type f -name "${ic_launcher_name}.*" -print -quit)"
          ic_launcher_ext="${ic_launcher_ext##*.}"

          find app/src -iname "${ic_launcher_name}*.${ic_launcher_ext}" \
          -exec magick mogrify -channel RGB -negate {} \+
       
          # find app/src \( -iname "${ic_launcher_name}*.png" -o -iname "${ic_launcher_name}*.webp" \) \
          # -exec magick mogrify -channel RGB -negate {} \+
          
          # find app/src -iname 'ic_launcher*.png' -exec magick mogrify -channel RGB -negate {} \+

      - run: yes | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Build APK
        run: |
          chmod +x ./gradlew
          ./gradlew :app:assemble${FLAV^}Release

      - name: List apks
        run: |
          find app/build/outputs/apk/ -name '*.apk' -exec echo '✅' {} \;

      - name: Sign APK
        env:
          KEYSTORE: ${{ secrets.SIGNING_KEY }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: |
          echo "${KEYSTORE}" | base64 -d > apksign.keystore
          find app/build/outputs/apk/ -name '*.apk' -exec \
          ${ANDROID_HOME}/build-tools/36.0.0/apksigner \
          sign --ks apksign.keystore --ks-pass env:SIGNING_STORE_PASSWORD {} \;

      - name: rename apk
        run: |
          APK_DIR=$(find app/build/outputs/apk/ -name '*.apk' -print -quit)
          APK_DIR=$(dirname $APK_DIR)
          VER_NAME=$(jq -r '.elements[0].versionName' ${APK_DIR}/output-metadata.json)

          shopt -s nocasematch
          for apk in "$APK_DIR"/*.apk; do
            if [[ $apk =~ ${APP_NAME} ]]; then
              break;
            fi
            RENAME_APK=$(sed -E "s/(app-[^-]+)(.*)/\1-${VER_NAME}\2/" <<< "$apk")
            RENAME_APK=${RENAME_APK/app-/${APP_NAME}-}
            RENAME_APK=${RENAME_APK/-unsigned/}
            if ! [[ $apk == ${RENAME_APK} ]]; then
              mv $apk ${RENAME_APK}
            fi
          done
          shopt -u nocasematch

          echo "VER_NAME=${VER_NAME}" >> $GITHUB_ENV
          echo "APK_DIR=${APK_DIR}" >> $GITHUB_ENV

################################
      - name: Commit APK Repo
        uses: actions/checkout@v6
        with:
          repository: "wrppg/apk"
          token: ${{ secrets.GH_APK_REPO }}
          path: "apk-repo"

      - run: |
          cd apk-repo
          pwd
          ls
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-action[bot]"
          git pull
          APP_FLAV_NAME="${APP_NAME}${FLAV:+"-$FLAV"}"
          echo "APP_FLAV_NAME=${APP_FLAV_NAME}" >> $GITHUB_ENV
          echo "${APP_FLAV_NAME} ${VER_NAME} update to ${VER_NAME}" > update.txt
          git add update.txt
          # git commit -m "update" && git push
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "update"
            git push
          fi
          
          # git diff --quiet && git diff --staged --quiet || (git commit -m "Update" && git push)
          
          cd -
          pwd
################################

      - name: build tag_name
        run: |
          # APP_FLAV_NAME="${APP_NAME}${FLAV:+"-$FLAV"}"
          tag_name="${VER_NAME}-${APP_FLAV_NAME}"
          
          echo "${tag_name}"
          echo "tag_name=${tag_name}" >> $GITHUB_ENV

      - name: Chech dup tag_name
        id: check-dup
        env:
          GH_TOKEN: ${{ secrets.GH_APK_REPO }}
        run: |
          gh release view -R wrppg/apk "${tag_name}" && echo "skip=true" >> $GITHUB_OUTPUT || true
          
      - name: Release
        if: steps.check-dup.outputs.skip != 'true'
        env:
          GH_TOKEN: ${{ secrets.GH_APK_REPO }}
        run: |
          # APP_FLAV_NAME="${APP_NAME}${FLAV:+"-$FLAV"}"
          # gh release create "${VER_NAME}-${APP_FLAV_NAME}" --title "${APP_FLAV_NAME} ${VER_NAME}" --repo wrppg/apk ${APK_DIR}/*.apk --notes $'Automate build\n'"update to ${VER_NAME}"

          gh release create "${tag_name}" --title "${APP_FLAV_NAME} ${VER_NAME}" --repo wrppg/apk ${APK_DIR}/*.apk --notes $'Automate build\n'"update to ${VER_NAME}"

          # gh release upload "${versionName}-${APP_FLAV_NAME}" ${APK_PATH_PREFIX}/*.apk

      - uses: actions/checkout@v6
        with:
          token: ${{ github.token }}
          path: "bff"

      - run: |
          cd bff
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-action[bot]"
          git pull
          sed -E "/${APP_NAME}/s/^[0-9]+/${VER_CODE}/" -i app_record.txt
          column -t app_record.txt > app_record.txt.tmp
          mv app_record.txt.tmp app_record.txt
          git add app_record.txt
          # git commit -m "update app_record.txt"
          # git commit -m "app_record.txt ${APP_NAME} to ${VER_CODE}"
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "app_record.txt ${APP_NAME} to ${VER_CODE}"
            git push
          fi
