name: Test - Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v4
      - env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # gh auth login --with-token <<<"${{ github.token }}"
          gh workflow run -R ${{ github.repository }} LS.yaml
